VOCABULARIO = {
    "arepa": "arepa",
    "berraco": "berrac",
    "boleta": "boleta",
    "cacharrear": "cacharr",
    "camello": "camell",
    "chicanear": "chican",
    "chimbo": "chimbo",
    "chino": "chino",
    "china": "china",
    "desparchado": "desparch",
    "embolatar": "embolat",
    "jartar": "jart",
    "joda": "jod",
    "mamera": "mamer",
    "mamón": "mamón",
    "ñero": "ñer",
    "paila": "pail",
    "parchar": "parch",
    "severo": "sever",
    "vuelta": "vuelta",
    "vueltas": "vueltas",
}
